global:
  scrape_interval:     15s
  evaluation_interval: 15s
rule_files:
scrape_configs:
  - job_name: prometheus
    static_configs:
      #Define Hosts monitorados pelo Prometheus
      - targets: ['localhost:9090','node:3000']